package app

import (
	"context"
	cryptorand "crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"math/rand/v2"
	"net"
	"net/http"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"golang.org/x/net/proxy"
)

// Runtime sockets live outside the persistent volume so their paths remain short.
// SOCKS authentication is an internal generation tag, not public proxy auth.
type torSession struct {
	ctrl    *control
	mu      sync.Mutex
	current *endpoint
}

var socksUserPattern = regexp.MustCompile(`(?:^| )SOCKS_USERNAME="([a-f0-9]+)"(?: |$)`)
var errFreshRestart = errors.New("used-IP retry limit reached; rebuilding this Tor instance from scratch")

// errBootstrapStuck marks a bootstrap phase that exceeded its time budget.
// The worker wipes this instance's Tor state and starts it over instead of
// retrying a process that is clearly wedged.
var errBootstrapStuck = errors.New("bootstrap did not finish; rebuilding this Tor instance from scratch")

// errServeFailures marks an instance whose verified circuit keeps failing to
// serve. Rotation did not help, so the worker wipes its Tor state and starts
// it over instead of retrying the same broken setup.
var errServeFailures = errors.New("consecutive serving failures; rebuilding this Tor instance from scratch")

// maxConsecutiveServeFailures is how many failed assignments in a row trigger
// a fresh restart of that instance.
const maxConsecutiveServeFailures = 3

func (s *torSession) setEndpoint(ep *endpoint) {
	s.mu.Lock()
	s.current = ep
	s.mu.Unlock()
}

func (s *torSession) events(ctx context.Context) {
	internalStreams := make(map[string]bool)
	defer func() {
		s.mu.Lock()
		defer s.mu.Unlock()
		if s.current != nil {
			s.current.cancel()
		}
	}()
	for {
		select {
		case <-ctx.Done():
			return
		case <-s.ctrl.done:
			return
		case event := <-s.ctrl.events:
			fields := strings.Fields(event)
			if len(fields) < 3 {
				continue
			}
			s.mu.Lock()
			ep := s.current
			s.mu.Unlock()
			if fields[0] == "CIRC" && ep != nil && fields[1] == ep.circuit && (fields[2] == "CLOSED" || fields[2] == "FAILED") {
				ep.cancel()
			}
			if fields[0] != "STREAM" {
				continue
			}
			// Directory streams are generated by Tor itself, not by a SOCKS
			// client. Interfering with them prevents consensus downloads. Their
			// target can be a real relay address; purpose appears only on NEW.
			if isInternalStream(fields) {
				internalStreams[fields[1]] = true
			}
			if internalStreams[fields[1]] {
				if fields[2] == "CLOSED" {
					delete(internalStreams, fields[1])
				}
				continue
			}
			if _, err := strconv.ParseUint(fields[1], 10, 64); err != nil {
				s.ctrl.Close()
				return
			}
			switch fields[2] {
			case "NEW", "NEWRESOLVE":
				match := socksUserPattern.FindStringSubmatch(event)
				if ep == nil || ep.ctx.Err() != nil || len(match) != 2 || match[1] != ep.token {
					_, _ = s.ctrl.command(ctx, "CLOSESTREAM "+fields[1]+" 1")
					continue
				}
				if _, err := s.ctrl.command(ctx, "ATTACHSTREAM "+fields[1]+" "+ep.circuit); err != nil {
					_, _ = s.ctrl.command(ctx, "CLOSESTREAM "+fields[1]+" 1")
				}
			case "DETACHED":
				// Never give Tor permission to retry on a different circuit.
				_, _ = s.ctrl.command(ctx, "CLOSESTREAM "+fields[1]+" 1")
			}
		}
	}
}

func isInternalStream(fields []string) bool {
	if len(fields) >= 5 && strings.HasPrefix(fields[4], "(Tor_internal):") {
		return true
	}
	for _, field := range fields {
		if field == "PURPOSE=DIR_FETCH" || field == "PURPOSE=DIR_UPLOAD" || field == "PURPOSE=DIRPORT_TEST" {
			return true
		}
	}
	return false
}

func RunWorkers(ctx context.Context, cfg Config, pool *Pool, runtimeDir string) *sync.WaitGroup {
	wg := &sync.WaitGroup{}
	for id := 1; id <= cfg.TorCount; id++ {
		wg.Add(1)
		go func(id int) {
			defer wg.Done()
			// Spread bootstrap and IP-check traffic without serializing startup.
			if !pause(ctx, time.Duration(rand.IntN(2000))*time.Millisecond) {
				return
			}
			backoff := 10 * time.Second
			for ctx.Err() == nil {
				err := runTor(ctx, cfg, pool, id, runtimeDir)
				if ctx.Err() != nil {
					break
				}
				if needsFreshRestart(err) {
					pool.state(id, "Restarting", 0, err)
					if resetErr := resetInstanceData(cfg.DataDir, id); resetErr != nil {
						pool.state(id, "Error", 0, resetErr)
						return
					}
					backoff = 10 * time.Second
					if !pause(ctx, jitter(backoff)) {
						break
					}
					continue
				}
				pool.state(id, "Error", 0, err)
				if !pause(ctx, jitter(backoff)) {
					break
				}
				backoff = min(60*time.Second, backoff*2)
			}
			pool.state(id, "Stopped", -1, nil)
		}(id)
	}
	return wg
}

func runTor(ctx context.Context, cfg Config, pool *Pool, id int, runtimeDir string) error {
	dataDir := filepath.Join(cfg.DataDir, "tor", strconv.Itoa(id))
	socketDir := filepath.Join(runtimeDir, strconv.Itoa(id))
	for _, dir := range []string{dataDir, socketDir} {
		if err := os.MkdirAll(dir, 0700); err != nil {
			return err
		}
	}
	controlPath, socksPath := filepath.Join(socketDir, "control"), filepath.Join(socketDir, "socks")
	// The previous child has been reaped before a restart reaches this point.
	for _, path := range []string{controlPath, socksPath} {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	config := torConfiguration(dataDir, controlPath, socksPath)
	configPath := filepath.Join(socketDir, "torrc")
	if err := os.WriteFile(configPath, []byte(config), 0600); err != nil {
		return err
	}
	cmd := exec.Command("tor", "-f", configPath)
	cmd.Stdout = &torLogWriter{id: id}
	cmd.Stderr = cmd.Stdout
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start Tor: %w", err)
	}
	processDone := make(chan struct{})
	var processErr error
	go func() { processErr = cmd.Wait(); close(processDone) }()
	defer func() {
		select {
		case <-processDone:
			return
		default:
		}
		_ = cmd.Process.Signal(syscall.SIGTERM)
		select {
		case <-processDone:
		case <-time.After(5 * time.Second):
			_ = cmd.Process.Kill()
			<-processDone
		}
	}()
	return superviseTor(ctx, cfg, pool, id, controlPath, socksPath, processDone, &processErr)
}

func torConfiguration(dataDir, controlPath, socksPath string) string {
	return fmt.Sprintf(`DataDirectory %s
SocksPort unix:%s NoIPv6Traffic NoOnionTraffic
ControlSocket %s
CookieAuthentication 0
ClientOnly 1
RunAsDaemon 0
AvoidDiskWrites 1
GeoIPFile /dev/null
GeoIPv6File /dev/null
__LeaveStreamsUnattached 1
Log notice stdout
`, strconv.Quote(dataDir), socksPath, strconv.Quote(controlPath))
}

func superviseTor(ctx context.Context, cfg Config, pool *Pool, id int, controlPath, socksPath string, processDone <-chan struct{}, processErr *error) error {
	pool.state(id, "Bootstrapping", 0, nil)
	bootCtx, bootCancel := context.WithTimeout(ctx, cfg.BootstrapTimeout)
	defer bootCancel()
	var conn net.Conn
	for {
		var err error
		conn, err = (&net.Dialer{}).DialContext(bootCtx, "unix", controlPath)
		if err == nil {
			break
		}
		select {
		case <-processDone:
			return fmt.Errorf("Tor exited during bootstrap: %v: %w", *processErr, errBootstrapStuck)
		default:
		}
		if !pause(bootCtx, 200*time.Millisecond) {
			return fmt.Errorf("waiting for Tor control socket: %w", errBootstrapStuck)
		}
	}
	ctrl := newControl(conn)
	defer ctrl.Close()
	if _, err := ctrl.command(bootCtx, "AUTHENTICATE"); err != nil {
		return fmt.Errorf("authenticate control connection: %w", errBootstrapStuck)
	}
	if _, err := ctrl.command(bootCtx, "SETEVENTS STREAM CIRC"); err != nil {
		return fmt.Errorf("subscribe to control events: %w", errBootstrapStuck)
	}
	sessionCtx, sessionCancel := context.WithCancel(ctx)
	defer sessionCancel()
	session := &torSession{ctrl: ctrl}
	go session.events(sessionCtx)
	for {
		lines, err := ctrl.command(bootCtx, "GETINFO status/bootstrap-phase")
		if err != nil {
			return fmt.Errorf("bootstrap: %w", errBootstrapStuck)
		}
		progress := bootstrapProgress(strings.Join(lines, " "))
		pool.state(id, "Bootstrapping", progress, nil)
		if progress == 100 {
			break
		}
		if !pause(bootCtx, time.Second) {
			return fmt.Errorf("bootstrap did not reach 100%% within %s: %w", cfg.BootstrapTimeout, errBootstrapStuck)
		}
	}
	bootCancel()
	backoff := 10 * time.Second
	usedStreak := 0
	for ctx.Err() == nil {
		pool.state(id, "Checking", 100, nil)
		err := cycle(ctx, cfg, pool, session, id, socksPath)
		if ctx.Err() != nil {
			return ctx.Err()
		}
		select {
		case <-ctrl.done:
			return errControlClosed
		default:
		}
		if shouldRestartForUsedIP(cfg, &usedStreak, err) {
			return errFreshRestart
		}
		if err != nil {
			pool.state(id, "Retrying", -1, err)
			backoff = min(60*time.Second, backoff*2)
		} else {
			backoff = 10 * time.Second
			pool.state(id, "Rotating", -1, nil)
		}
		// NEWNYM is advisory and may be rate limited. Explicit circuit creation,
		// closure and a fresh IP check enforce the application's actual policy.
		if !pause(ctx, jitter(backoff)) {
			return ctx.Err()
		}
		if _, err := ctrl.command(ctx, "SIGNAL NEWNYM"); err != nil {
			return err
		}
	}
	return ctx.Err()
}

func shouldRestartForUsedIP(cfg Config, streak *int, err error) bool {
	if cfg.UniqueIP && errors.Is(err, errUsedIP) {
		*streak++
	} else {
		*streak = 0
	}
	return cfg.UniqueIP && *streak >= cfg.MaxUsedIPRetries
}

// needsFreshRestart reports whether an instance must discard its Tor state and
// start over instead of retrying in place.
func needsFreshRestart(err error) bool {
	return errors.Is(err, errFreshRestart) || errors.Is(err, errBootstrapStuck) || errors.Is(err, errServeFailures)
}

func resetInstanceData(dataDir string, id int) error {
	if id < 1 {
		return errors.New("invalid instance ID for reset")
	}
	root, err := filepath.Abs(filepath.Join(dataDir, "tor"))
	if err != nil {
		return err
	}
	target := filepath.Join(root, strconv.Itoa(id))
	if filepath.Dir(target) != root || target == root {
		return errors.New("instance reset path escapes Tor data directory")
	}
	return os.RemoveAll(target)
}

func cycle(ctx context.Context, cfg Config, pool *Pool, session *torSession, id int, socksPath string) error {
	checkCtx, cancel := context.WithTimeout(ctx, cfg.ConnectTimeout)
	defer cancel()
	lines, err := session.ctrl.command(checkCtx, "EXTENDCIRCUIT 0 purpose=general")
	if err != nil {
		return err
	}
	var circuit string
	for _, line := range lines {
		if strings.HasPrefix(line, "EXTENDED ") {
			circuit = strings.TrimPrefix(line, "EXTENDED ")
		}
	}
	if value, err := strconv.ParseUint(circuit, 10, 64); err != nil || value == 0 {
		return errors.New("Tor returned an invalid circuit ID")
	}
	defer func() { _, _ = session.ctrl.command(ctx, "CLOSECIRCUIT "+circuit) }()
	for {
		lines, err = session.ctrl.command(checkCtx, "GETINFO circuit-status")
		if err != nil {
			return err
		}
		built := false
		for _, line := range strings.Split(strings.Join(lines, "\n"), "\n") {
			f := strings.Fields(line)
			if len(f) >= 2 && f[0] == circuit && f[1] == "BUILT" {
				built = true
			}
		}
		if built {
			break
		}
		if !pause(checkCtx, 200*time.Millisecond) {
			return fmt.Errorf("building circuit: %w", checkCtx.Err())
		}
	}
	epCtx, epCancel := context.WithCancel(ctx)
	ep := &endpoint{id: id, circuit: circuit, ctx: epCtx, cancel: epCancel, done: make(chan struct{})}
	defer epCancel()
	var token [16]byte
	if _, err := cryptorand.Read(token[:]); err != nil {
		return err
	}
	ep.token = hex.EncodeToString(token[:])
	dialer, err := proxy.SOCKS5("unix", socksPath, &proxy.Auth{User: ep.token, Password: "generation"}, &net.Dialer{Timeout: cfg.ConnectTimeout})
	if err != nil {
		return err
	}
	ep.dial = func(ctx context.Context, network, address string) (net.Conn, error) {
		if err := ep.ctx.Err(); err != nil {
			return nil, err
		}
		dialCtx, dialCancel := context.WithTimeout(ctx, cfg.ConnectTimeout)
		stop := context.AfterFunc(ep.ctx, dialCancel)
		defer stop()
		defer dialCancel()
		conn, err := dialer.(proxy.ContextDialer).DialContext(dialCtx, network, address)
		if err != nil {
			return nil, err
		}
		return guardConnection(ep.ctx, conn, cfg.IdleTimeout), nil
	}
	session.setEndpoint(ep)
	defer session.setEndpoint(nil)
	ip, err := checkIP(checkCtx, cfg.IPCheckURL, ep.dial, cfg.ConnectTimeout)
	if err != nil {
		return fmt.Errorf("IP check: %w", err)
	}
	ep.ip = ip
	for {
		ready, err := pool.publish(ctx, ep)
		if err != nil {
			return err
		}
		if !ready {
			return fmt.Errorf("IP %s is used, reserved, or its circuit expired", ip)
		}
		select {
		case <-ep.done:
			// The assigned request or tunnel finished; its result is in lastErr.
		case <-ep.ctx.Done():
			pool.withdraw(ep)
			return errors.New("verified circuit closed")
		case <-session.ctrl.done:
			pool.withdraw(ep)
			return errControlClosed
		}
		if ep.lastErr != nil && pool.consecutiveFailures(ep.id) >= maxConsecutiveServeFailures {
			// Rotation did not help; rebuild this instance from scratch.
			pool.withdraw(ep)
			return fmt.Errorf("%w: %v", errServeFailures, ep.lastErr)
		}
		if cfg.UniqueIP || ep.lastErr != nil {
			// Unique mode rotates after every assignment; reuse mode rotates
			// after a failed one so the next request gets a fresh circuit.
			pool.withdraw(ep)
			return ep.lastErr
		}
		// Reuse mode keeps a healthy verified circuit and serves the next
		// assignment with the same IP instead of rotating.
		ep.done = make(chan struct{})
		ep.once = sync.Once{}
		ep.lastErr = nil
	}
}

func checkIP(ctx context.Context, address string, dial dialFunc, timeout time.Duration) (string, error) {
	transport := &http.Transport{DialContext: dial, DisableKeepAlives: true, TLSHandshakeTimeout: timeout, ResponseHeaderTimeout: timeout, MaxResponseHeaderBytes: 64 * 1024}
	defer transport.CloseIdleConnections()
	client := &http.Client{Transport: transport, Timeout: timeout, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, address, nil)
	if err != nil {
		return "", err
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 65))
	if err != nil {
		return "", err
	}
	ip, err := netip.ParseAddr(strings.TrimSpace(string(body)))
	if err != nil || !ip.Is4() || !ip.IsGlobalUnicast() || ip.IsPrivate() {
		return "", errors.New("IP checker must return one public IPv4 address as plain text")
	}
	return ip.String(), nil
}

func bootstrapProgress(line string) int {
	for _, field := range strings.Fields(line) {
		if strings.HasPrefix(field, "PROGRESS=") {
			n, _ := strconv.Atoi(strings.TrimPrefix(field, "PROGRESS="))
			return max(0, min(n, 100))
		}
	}
	return 0
}

func pause(ctx context.Context, duration time.Duration) bool {
	t := time.NewTimer(duration)
	defer t.Stop()
	select {
	case <-ctx.Done():
		return false
	case <-t.C:
		return true
	}
}

func jitter(duration time.Duration) time.Duration {
	return duration + time.Duration(rand.IntN(1000))*time.Millisecond
}

type torLogWriter struct {
	id     int
	mu     sync.Mutex
	buffer string
}

func (w *torLogWriter) Write(data []byte) (int, error) {
	w.mu.Lock()
	defer w.mu.Unlock()
	w.buffer += string(data)
	for {
		line, rest, ok := strings.Cut(w.buffer, "\n")
		if !ok {
			break
		}
		w.buffer = rest
		if strings.Contains(line, "[warn]") || strings.Contains(line, "[err]") {
			slog.Warn(strings.TrimSpace(line), "instance", w.id)
		} else {
			slog.Debug(strings.TrimSpace(line), "instance", w.id)
		}
	}
	if len(w.buffer) > 65536 {
		w.buffer = ""
	}
	return len(data), nil
}
